#config_version=5

##! mode: base
mode:
  start_events: ball_starting
  priority: 100



autofire_coils:
  outhole_sd1_game:
    coil: c_outhole_sd1
    switch: s_outhole_sd1
  outhole_sd2_game:
    coil: c_outhole_sd2
    switch: s_outhole_sd2

coil_player:
  s_slingshot_right_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_slingshot_left_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_slingshot_right_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_slingshot_left_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_popbmp_r_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_popbmp_l_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_flipper_right_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_flipper_left_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_flipper_right_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_flipper_left_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_outhole_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_outhole_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_shootlane_sd1_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200
  s_shootlane_sd2_active:
    c_viking_eyes:
      action: pulse
      pulse_ms: 200

event_player:
  s_killflip_sd2_active:
    reenable_sd1_flippers:
      delay: 2s
  s_killflip_sd1_active:
    reenable_sd2_flippers:
      delay: 2s
  machine_var_current_ball{value==6}:
    game_ending

variable_player:
  mode_base_started:
    current_ball:
      int: 1
      action: set
      type: machine
  s_outhole_sd1_active:
    current_ball:
      int: 1
      type: machine
  s_outhole_sd2_active:
    current_ball:
      int: 1
      type: machine
  s_slingshot_right_sd1_active:
    p2_score:
      int: 1000
      type: machine
  s_slingshot_left_sd1_active:
    p2_score:
      int: 1000
      type: machine
  s_slingshot_right_sd2_active:
    p1_score:
      int: 1000
      type: machine
  s_slingshot_left_sd2_active:
    p1_score:
      int: 1000
      type: machine
  s_killflip_sd1_active:
    p2_score:
      int: 10000
      type: machine
  s_killflip_sd2_active:
    p1_score:
      int: 10000
      type: machine
  s_spinner_sd1_active:
    p2_score:
      int: 500
      type: machine
  s_spinner_sd2_active:
    p1_score:
      int: 500
      type: machine
  s_1000pts_sd1_active:
    p2_score:
      int: 1000
      type: machine
  s_1000pts_sd2_active:
    p1_score:
      int: 1000
      type: machine
  s_100pts_sd1_active:
    p2_score:
      int: 100
      type: machine
  s_100pts_sd2_active:
    p1_score:
      int: 100
      type: machine
  s_outhole_sd1_active:
    p2_score:
      int: 10000
      type: machine
  s_outhole_sd2_active:
    p1_score:
      int: 10000
      type: machine
  s_popbmp_l_active:
    p1_score:
      int: 50
      type: machine
  s_popbmp_r_active:
    p2_score:
      int: 50
      type: machine
